version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.dokka:dokka-gradle-plugin
    versions:
    - 1.4.20
    - 1.4.30
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
